### ISSUE TITLE
Problem, ErrorID #366533-968

### ISSUE THREAD

**Issue by W00DY-W00DP4CK3R** [ByteWiseOwl/arknights_recruit_helper#1]
Hello

Programm told me to send you the Error ID #366533-968.
I don't really know why i should do this but it told me.

Sincerly,
Woody Woodpacker

**Comment by ByteWiseOwl** [comment]
Hello Woody Woodpecker,

Thank you very much for your interest. Could you give me more details? As it is likely a message from a code that I have used, and not from my own code, I cannot identify it as such. 

However, I would be happy to help you get the program running.

Sincerely,
ByteWiseOwl

**Comment by W00DY-W00DP4CK3R** [comment]
I'll think everything is set now...

Sincerly
Woody Woodpacker
